### PR TITLE
Implement Settings API

### PR DESCRIPTION
**Pull request by col-panic**
I already use it internally and it works - tests not yet enclosed due to #33

### CODE REVIEW

**Comment by joachimprinzbach** [comment]
Thanks for your contribution! 
Could you fix the CodeQuality check please?

**Comment by joachimprinzbach** [comment]
@culmat Could you review the code changes pls?

**Comment by col-panic** [comment]
Any interest in this? I'm currently deciding on whether to spend any more work on contributing or not ?!

**Comment by MarkusTiede** [comment]
@col-panic - thanks for the reminder; @culmat seems to be currently inactive.

@col-panic : Would you be interested in becoming an active contributor / maintainer of this package? For now I (unfortunately) can't tell whether we'll be actively driving this in the upcoming future.

**Comment by col-panic** [comment]
I am currently developing into my own fork of the project, for the requirements we have. So yes, w.r.t. the developments we do I could actively contribute them to your repo.

**Comment by MarkusTiede** [comment]
Thanks for the quick response: I've sent you an invitation for write access (including PRs) for this repo.

**Comment by col-panic** [comment]
Thanks @MarkusTiede

**Comment by col-panic** [comment]
@MarkusTiede please remove the requirement that @culmat reviews pull requests - I want to provide patches via PRs to be transparent, but am not allowed to approve them by my own

**Review by culmat — COMMENTED** [review]
Merci

**Comment by col-panic** [comment]
Tests are yet missing! I wanted to check on those as soon as the maven test was running again :)

**Pull request merged**
