### PR TITLE
[WIP] Use models for body params

### PR DESCRIPTION
**Pull request by graywolf336**
**DO NOT MERGE YET**

I am currently rewriting a few things to make them how I originally envisioned it. Including the requests and the additional request objects passed into the body, ideally we will always use what is already defined and only create new request objects when absolutely required (such as the `ChannelHistoryRequest`).

### CODE REVIEW

**Comment by graywolf336** [comment]
@rynefagin and @rh-imcmahon do you mind setting your tabs to use spaces inside of Eclipse? Just because it looks better here on GitHub and so we are consistent. Thanks!!

**Comment by graywolf336** [comment]
@rynefagin I need to update the docker imge to point to the latest changes in the develop branch, what's required to get that changed?

**Comment by rynefagin** [comment]
@graywolf336 in the dockerfile, /src/main/docker, the param ENV RC_VERSION <<experimental|develop|latest>> if you'd like to change it.

**Comment by rynefagin** [comment]
What are your thoughts around the docker ITs? Do you see value in having this?

**Comment by graywolf336** [comment]
> @graywolf336 in the dockerfile, /src/main/docker, the param ENV RC_VERSION <<experimental|develop|latest>> if you'd like to change it.

Hmmm I tried that, but some reason `develop` kept erroring out on me. I'll try it again tomorrow.

> What are your thoughts around the docker ITs? Do you see value in having this?

Yes I do see a big value in having it. Actually helped me out when I was refactoring a few things and then it will help us know when something has changed in this repository or upstream and requires changes. :+1:

**Comment by rynefagin** [comment]
> Hmmm I tried that, but some reason develop kept erroring out on me. I'll try it again tomorrow.

interesting...i'd have to see the logs, did the containers build/start correctly or was it an error when you ran the tests?  You can always try to nuke the containers and images and start from scratch.

**Comment by graywolf336** [comment]
What's the difference between `experimental` and `develop`?

**Comment by graywolf336** [comment]
@culmat Just to let you know - I sent you an email about a few things, hopefully it's an email you still use as I got it off GitHub.

**Comment by graywolf336** [comment]
@culmat ....This was still marked as a work in progress. 😬

**Pull request merged**
