### PR TITLE
Changes to reflect new rocket.chat api

### PR DESCRIPTION
**Pull request by graywolf336**
Started work on implementing the new rest api which is coming out in the next version of Rocket.Chat, this and #4 are pretty close although we took a different approach to a few things.

The general work is done, however I will be proposing changes to Rocket.Chat's `chat.postMessage` API as it isn't consistent with the rest of the APIs. The work that still needs to be completed is adding the individual calls to the client. My whole idea was to make everything as "object" as possible with getters and setters so this client would be easy to understand. The other main idea was the class `RocketChatClient` contained all of the REST API methods and actual methods with parameters that make since instead of generic methods on the client.

### CODE REVIEW

**Comment by rynefagin** [comment]
at first glance I like your approach, I'll have to review it in detail later today-nice work.

**Comment by graywolf336** [comment]
@rynefagin Awesome, let me know if you have any questions

**Review by rynefagin — COMMENTED** [review]
Huge leap forward for this project. :D

**Comment by graywolf336** [comment]
Awesome, hopefully we can get this merged and then each take an area of the methods to add and get it fully finished as team work 😀

**Comment by rynefagin** [comment]
With the holidays approaching I plan on having more time to work on this, might have a couple of folks on my team that would be interesting in making updates as well. I've been using the rest API documentation as like a backlog-if you have any thoughts on how to segregate work let me know. I didn't see version notes on Rocket.Chats API Documenataion (not that I was looking hard) but if there is some develop docs outlining what those changes are it would be helpful. Looking at the commit history looks like you're the guy makin the changes, even just some direction would be helpful at a minimum

**Comment by graywolf336** [comment]
@rynefagin Indeed, I have spent most of last week in the new rest api so I am the guy. 😜 It was just added to version `0.48` of Rocket.Chat which was released last night. I would suggest one of us takes on the users, channels, groups, and direct messages piece and then go from there. How's that sound?

**Comment by graywolf336** [comment]
@rynefagin As an update, I have been working on the documentation of the `/api/v1/chat.postMessage` and will be submitting a pull request to Rocket.Chat itself to make that rest api endpoint accept `roomId` instead of just the channel name which will make things easier when you know the room's id and not the name....and fixing a bug I accidently introduced. 🙈

**Comment by rynefagin** [comment]
@graywolf336 nice! I'll have to adjust the docker image to pull the changes if you write an integration test that maven fires during the IT phase.  I'll be working on the channel functionality when I can.

**Comment by graywolf336** [comment]
@rynefagin Sounds good to me. 👍 You can take a read at the [chat.postMessage](https://rocket.chat/docs/developer-guides/rest-api/chat/postmessage) documentation now, I plan on building out full functionality including attachment supports - except file uploads won't be supported since the rest api doesn't support that...yet.

**Pull request merged**
