### PR TITLE
WIP: [DO NOT MERGE] - Adding additional v1 functionality

### PR DESCRIPTION
**Pull request by rynefagin**
@graywolf336 please take a look and provide feedback.

### CODE REVIEW

**Comment by graywolf336** [comment]
I'll take a look here shortly, only thing that comes to mind right now is your commit history - can you clean it up somehow? Just would make the commit history on this repository not look very good in my opinion.

**Comment by graywolf336** [comment]
Another thing, we need to establish some sort of spacing enforcer and code style as yours and mine aren't a little bit different.

**Comment by rynefagin** [comment]
Yeah i noticed that 😖 I'll clean it up.  if you have an eclipse formatter file i can import it or if you want to go the checkstyle route. Thanks my friend! 👍

**Comment by graywolf336** [comment]
You might be in luck, I have a eclipse clean-up style and format thing somewhere. Let me verify the one I currently have is decent and then see about exporting it.

**Comment by graywolf336** [comment]
@rynefagin Check out my pull request, I included the Eclipse Cleanup settings I use. I'm also going to add an `.editorconfig` to hopefully unify things even more.

**Comment by rynefagin** [comment]
Thanks @graywolf336 for the review and cleanup settings 😸

**Comment by graywolf336** [comment]
@rynefagin No problem, once you open another pull request with the new items I will review it as well...as there are a couple things you're doing I think we could do differently/better, but they're just my opinion and are open for discussion 100%! (Especially since I'm not the maintainer of this repository)

**Pull request closed without merging**
